DROP TABLE students;
DROP TABLE groups;

-- task 1
CREATE TABLE students (
    id NUMBER PRIMARY KEY,
    name VARCHAR2 NOT NULL,
    group_id NUMBER FOREIGN KEY
);

CREATE TABLE groups (
    id NUMBER PRIMARY KEY,
    name VARCHAR2 NOT NULL,
    c_val NUMBER DEFAULT
)

-- task 2
CREATE OR REPLACE TRIGGER check_student_id
BEFORE UPDATE OR INSERT

END;

CREATE OR REPLACE TRIGGER increment_student_id
BEFORE UPDATE OR INSERT
END;

CREATE OR REPLACE TRIGGER check_student_name
BEFORE UPDATE OR INSERT
END;

CREATE OR REPLACE TRIGGER check_group_id
BEFORE UPDATE OR INSERT
END;

CREATE OR REPLACE TRIGGER increment_group_id
BEFORE UPDATE OR INSERT
END;

CREATE OR REPLACE TRIGGER check_group_name
BEFORE UPDATE OR INSERT
END;
